FROM node:latest

WORKDIR /app
COPY package*.json ./
COPY . .

ARG API_URL
ARG APP_NAME

ENV HOST 0.0.0.0
ENV PORT 3000

ENV API_URL $API_URL
ENV APP_NAME $APP_NAME

ENV KEYCLOAK_AUTHSERVERURL $KEYCLOAK_AUTHSERVERURL
ENV KEYCLOAK_REALM $KEYCLOAK_REALM
ENV KEYCLOAK_CLIENTID $KEYCLOAK_CLIENTID
ENV KEYCLOAK_CLIENTSECRET $KEYCLOAK_CLIENTSECRET
ENV KEYCLOAK_REDIRECTURI $KEYCLOAK_REDIRECTURI
ENV KEYCLOAK_ENCRYPTIONALGORITHM $KEYCLOAK_ENCRYPTIONALGORITHM
ENV KEYCLOAK_ENCRYPTIONKEYPATH $KEYCLOAK_ENCRYPTIONKEYPATH
ENV KEYCLOAK_ENCRYPTIONKEY $KEYCLOAK_ENCRYPTIONKEY

RUN npm install
RUN npm run build

EXPOSE 3000

# start command
CMD [ "npm", "run", "start" ]
